# Generated by Django 4.0.6 on 2022-08-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.CharField(max_length=45, unique=True)),
                ('user_phone', models.CharField(max_length=11)),
                ('current_address', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255)),
                ('user_allergy', models.CharField(blank=True, max_length=255, null=True)),
                ('user_nickname', models.CharField(max_length=45, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
