# Generated by Django 4.0.6 on 2022-08-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_current_address_alter_user_login_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_password',
            field=models.CharField(default='', max_length=45),
        ),
    ]
