# Generated by Django 4.0.6 on 2022-08-06 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_created_at_user_groups_user_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='login_password',
        ),
    ]
